## Libraries in Python
### Libraries are collection of functions and method which allows user to perform many actions without writting the code

### 1. NumPy (Numerical Python is a core library for numeric and scientific cumputing. It consists of multi -  dimensional array objects and a collection of routines for processing those arrays

### ---  Some numpy functions  ---

### Difference between array and lists --- lists can be a collection of non-homogeneous elements but array is collection of homogeneous elements 

### 1. Single dimensional array

In [93]:
import numpy as np
# Converting list into array---
n1 = np.array([10,20,30,40,50,60])
n1

array([10, 20, 30, 40, 50, 60])

### 2. Multi dimensional array

In [94]:
n2 = np.array([[10,20,30,40,50,60],[50,60,70,80,90,100]]); n2 # both array length should be equal.i.e. 6 elements in both arrays

array([[ 10,  20,  30,  40,  50,  60],
       [ 50,  60,  70,  80,  90, 100]])

### 3. numpy array initializing with zero

In [95]:
zero_array = np.zeros((2,4));zero_array # first element is for rows and second is for colums, value will be 0 by default

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [96]:
zero_arr = np.ones((2,3)); zero_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

### 4. numpy array initializing witth same number

In [97]:
same_array = np.full((2,4),10); same_array # same as zeros array but it fills the given value

array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

### 5. numpy array initializing with range

In [98]:
range_np = np.arange(10,51);range_np

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

### 6. numpy array initializing with range and step in between

In [99]:
range_np_step = np.arange(0,101,10); range_np_step # 10 is the gap between start and end value

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

### 7. numpy array with random numbers

In [100]:
random_np = np.random.randint(10,1001,5); random_np # 10 is starting value, 1001 is end value, 5 is number of values we need

array([778, 894, 980, 437, 981])

In [101]:
random_n = np.random.randn(2,4); print(random_n); print("-----------------------------")#generates numbers from uniform distribution.
random_n1 = np.random.rand(3,4); print(random_n1); print("-----------------------------")#generates numbers from normal distribution.
random_n2 = np.random.randint(1,101,(2,9)); print(random_n2)

[[ 0.30484034 -0.03822323  0.15422282  0.99512124]
 [-1.33465553  1.90248945  0.69818024 -0.32121556]]
-----------------------------
[[0.60498244 0.88013032 0.33701918 0.12626953]
 [0.57566357 0.92653896 0.11885541 0.50222364]
 [0.70144198 0.88560017 0.29346608 0.88625089]]
-----------------------------
[[30 22 11 29 91 77  4 10 25]
 [21  7 29 95 65 60 32 98 57]]


### 8. How to check and change the shape of an array

In [102]:
n1 = np.array([[2,3,4],[5,6,7]]);n1

array([[2, 3, 4],
       [5, 6, 7]])

In [103]:
n1.shape

(2, 3)

In [104]:
n1.shape = (6,1)

In [105]:
n1

array([[2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [106]:
n1.shape = (3,2)

In [107]:
n1

array([[2, 3],
       [4, 5],
       [6, 7]])

In [108]:
n1.reshape(1,6)

array([[2, 3, 4, 5, 6, 7]])

In [109]:
#linspace --- this fuction used to create equally spaced elements array
linarray = np.linspace(1,20,22); linarray

array([ 1.        ,  1.9047619 ,  2.80952381,  3.71428571,  4.61904762,
        5.52380952,  6.42857143,  7.33333333,  8.23809524,  9.14285714,
       10.04761905, 10.95238095, 11.85714286, 12.76190476, 13.66666667,
       14.57142857, 15.47619048, 16.38095238, 17.28571429, 18.19047619,
       19.0952381 , 20.        ])

In [110]:
# --- another way to generate equally spaced elements array using linspace
linarray1 = np.linspace(1,101,22).reshape(2,11); linarray1

array([[  1.        ,   5.76190476,  10.52380952,  15.28571429,
         20.04761905,  24.80952381,  29.57142857,  34.33333333,
         39.0952381 ,  43.85714286,  48.61904762],
       [ 53.38095238,  58.14285714,  62.9047619 ,  67.66666667,
         72.42857143,  77.19047619,  81.95238095,  86.71428571,
         91.47619048,  96.23809524, 101.        ]])

In [111]:
linarray.reshape(1,22)

array([[ 1.        ,  1.9047619 ,  2.80952381,  3.71428571,  4.61904762,
         5.52380952,  6.42857143,  7.33333333,  8.23809524,  9.14285714,
        10.04761905, 10.95238095, 11.85714286, 12.76190476, 13.66666667,
        14.57142857, 15.47619048, 16.38095238, 17.28571429, 18.19047619,
        19.0952381 , 20.        ]])

In [112]:
# 3d array
arr1 = np.zeros((5,2,8)); arr1


array([[[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]]])

In [113]:
5 + arr1

array([[[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]],

       [[5., 5., 5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5., 5., 5.]]])

In [114]:
arr2 = np.random.randint(1,101,20).reshape(5,4)

In [115]:
arr2

array([[74, 78, 35, 34],
       [51,  2, 64, 64],
       [40, 89, 16,  5],
       [28, 52, 35, 96],
       [50, 56, 28, 99]])

In [116]:
#identity metrix --- eye/identity
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [117]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [118]:
np.eye(4).reshape(2,8)

array([[1., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 1.]])

In [119]:
# Slicing in array
arr1 = np.random.randint(1,101,(5,4)); arr1

array([[18, 75, 15,  1],
       [67, 36, 91, 67],
       [13, 77, 54, 47],
       [75, 25,  1, 67],
       [ 3, 23, 62, 14]])

In [120]:
print("`print starting three rows")
print(arr1[0:3])
print("------------------------")
print("print only starting three columns and rows")
print(arr1[0:3,0:3])
print("------------------------")
print("print rows 4 and 5 columns 2 to 4")
print(arr1[3:,1:])
print("------------------------")
print("print rows 4 and 5 columns 3 and 4")
print(arr1[2:4,1:3])
print("------------------------")
print("print rows 4 and 5 columns 1 and 4")
print(arr1[2:4,::3])

`print starting three rows
[[18 75 15  1]
 [67 36 91 67]
 [13 77 54 47]]
------------------------
print only starting three columns and rows
[[18 75 15]
 [67 36 91]
 [13 77 54]]
------------------------
print rows 4 and 5 columns 2 to 4
[[25  1 67]
 [23 62 14]]
------------------------
print rows 4 and 5 columns 3 and 4
[[77 54]
 [25  1]]
------------------------
print rows 4 and 5 columns 1 and 4
[[13 47]
 [75 67]]


In [121]:
# squareroot of array
arr3 = np.array([16,25,81,121])
np.sqrt(arr3)

array([ 4.,  5.,  9., 11.])

### Joining numpy arrays --- (There are three ways to join numpy arrays)
### 1. vstack --- (verticle stack)

In [122]:
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
n3 = np.array([70,80,90])
np.vstack((n1,n2,n3))

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

### 2. hstack --- (Horizontal stack)

In [123]:
np.hstack((n1,n2,n3))

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

### 3. column_stack --- (Stack columns)

In [124]:
np.column_stack((n1,n2,n3))

array([[10, 40, 70],
       [20, 50, 80],
       [30, 60, 90]])

### Intersect and setdiff of numpy array

In [125]:
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([50,60,70,80,90])

### intersect1d --- (This function returns the common values in two or arrays)

In [126]:
np.intersect1d(n1,n2)

array([50, 60])

### setdiff1d --- (This function returns the unique values in two arrays)

In [127]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [128]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

### How to calculate intersec and setdiff1d values for more than two arrays

In [129]:
#from functools import reduce
import numpy as np
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([20,100,110])
n3 = np.array([20,1,2,3])
print(n1,n2,n3)

[10 20 30 40 50 60] [ 20 100 110] [20  1  2  3]


In [130]:
#n1_intersec = reduce(np.intersect1d,(n1,n2,n3)); print(n1_intersec)

In [131]:
#n1_set = reduce(np.setdiff1d,(n1,n2,n3)); print(n1_set)

In [132]:
#n2_set = reduce(np.setdiff1d,(n2,n1,n3)); print(n2_set)

In [133]:
#n3_set = reduce(np.setdiff1d,(n3,n2,n1)); print(n3_set)

### Addition of numpy arrays

### 1. np.sum  ( [ n1 , n2 ] )

In [134]:
n1 = np.array([10,20])
n2 = np.array([30,40])
np.sum([n1,n2])

100

### 2. np.sum  ( [ n1 , n2 ] , axis = 0 )

In [135]:
np.sum([n1,n2],axis = 0)

array([40, 60])

### 3. np.sum  ( [ n1 , n2 ] , axis = 1 )

In [136]:
np.sum([n1,n2],axis = 1)

array([30, 70])

## NumPy array mathematics

In [137]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [138]:
n1 += 100
n1

array([[101, 102, 103, 104],
       [105, 106, 107, 108]])

In [139]:
n1 -= 50
n1

array([[51, 52, 53, 54],
       [55, 56, 57, 58]])

In [140]:
n1 *= 2
n1

array([[102, 104, 106, 108],
       [110, 112, 114, 116]])

In [141]:
n1 = n1/2
n1

array([[51., 52., 53., 54.],
       [55., 56., 57., 58.]])

## Numpy math functions --- (Mean, Median and std)

In [142]:
n1 = np.array([[1,2,3,4],[5,6,7,8]])
n1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [143]:
np.mean(n1)

4.5

In [144]:
np.median(n1)

4.5

In [145]:
np.std(n1)

2.29128784747792

## NumPy Save & Load
### 1. NumPy Save

In [146]:
numP1 = np.array([10,20,30,40,50,60,70,80,90]); numP1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [147]:
np.save("My_NumPy",numP1)

In [148]:
new_n1 = np.load("My_NumPy.npy")

In [149]:
new_n1

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

## 2. Pandas --- (Import pandas as pd)
### Pandas stands for Panel Data and is the core library for data manipulation and data analysis
### Pandas Data Structure
### A) Series Object --- Single dimensional data
### B) Data frame --- Multi-dimensional data

In [150]:
import pandas as pd

In [151]:
len(dir(pd))

138

### A) Series Object --- (Series Object is an one-dimensional labeled array)

In [152]:
# Create series object
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
print(s1)
print(type(s1))
# the number series starting from 0 is index

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>


### --- User can change the value of index using index function like shown below

In [153]:
s1 = pd.Series([5,4,3,2,1], index=range(1,6))
s1

1    5
2    4
3    3
4    2
5    1
dtype: int64

In [154]:
s1 = pd.Series([1,2,3,4,5], index = ['a','b','c','d','e']); s1

a    1
b    2
c    3
d    4
e    5
dtype: int64

### Series Object as dict { }

In [155]:
s2 = pd.Series({"A":10,"B":20,"C":30,"D":40})
s2

A    10
B    20
C    30
D    40
dtype: int64

In [156]:
s3 = pd.Series({"A":10,"B":20,"C":30,"D":40},index = ['B','C','A','D','A5']);s3

B     20.0
C     30.0
A     10.0
D     40.0
A5     NaN
dtype: float64

### Extracting Individual Elements

In [157]:
s4 = pd.Series([1,2,3,4,5,6],index = ['A','B','C','D','E','F'])
print(s4[4])
print("--------------")
print(s4[:4])
print("--------------")
print(s4[2:])
print("--------------")
print(s4[::2])
print("--------------")
print(s4[-4:-1])

5
--------------
A    1
B    2
C    3
D    4
dtype: int64
--------------
C    3
D    4
E    5
F    6
dtype: int64
--------------
A    1
C    3
E    5
dtype: int64
--------------
C    3
D    4
E    5
dtype: int64


In [158]:
d1 = pd.Series({"name1":"Python","name2":"HTML","name3":"CSS"})
print(d1)
print("-----------------")
print(d1["name1"])

name1    Python
name2      HTML
name3       CSS
dtype: object
-----------------
Python


### Basic math operations on series

In [159]:
s1 = pd.Series([1,2,3,4,5,6,7],index = range(1,8))
s2 = pd.Series([10,20,30,40,50,60,70,80],index = range(1,9))
print(s1+5)
print("---------------")
print(s1+s2)

1     6
2     7
3     8
4     9
5    10
6    11
7    12
dtype: int64
---------------
1    11.0
2    22.0
3    33.0
4    44.0
5    55.0
6    66.0
7    77.0
8     NaN
dtype: float64
